#!/usr/bin/env python3

import argparse
import json
from pathlib import Path

import h5py
import numpy as np


BACKBONE_CLASSES = ("N", "CA", "C", "O")


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Inject a martini_rbm_cross_potential node from a generated "
            "backbone cross-table artifact into one or more prepared .up files."
        )
    )
    parser.add_argument(
        "--artifact",
        type=Path,
        required=True,
        help="HDF5 artifact generated by build_backbone_cross_interaction_table.py",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Optional manifest describing .up files to update.",
    )
    parser.add_argument(
        "--up-files",
        nargs="*",
        default=[],
        help="Direct list of .up files to update.",
    )
    parser.add_argument(
        "--overwrite-existing",
        type=int,
        choices=[0, 1],
        default=1,
        help="Replace an existing martini_rbm_cross_potential node if present.",
    )
    return parser.parse_args()


def require_file(path: Path):
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def decode_bytes_array(arr):
    out = []
    for item in arr:
        if isinstance(item, (bytes, np.bytes_)):
            out.append(item.decode("utf-8", errors="ignore").strip())
        else:
            out.append(str(item).strip())
    return np.asarray(out, dtype=object)


def load_manifest_paths(manifest_path: Path):
    with manifest_path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)

    if isinstance(data, dict):
        if isinstance(data.get("systems"), list):
            items = data["systems"]
        elif isinstance(data.get("up_files"), list):
            items = data["up_files"]
        else:
            raise ValueError(f"Unsupported manifest schema: {manifest_path}")
    elif isinstance(data, list):
        items = data
    else:
        raise ValueError(f"Unsupported manifest top-level type: {type(data)}")

    paths = []
    for item in items:
        raw_path = None
        if isinstance(item, str):
            raw_path = item
        elif isinstance(item, dict):
            raw_path = item.get("up_file") or item.get("upside_input")
        if not raw_path:
            continue
        candidate = Path(raw_path).expanduser()
        if not candidate.is_absolute():
            candidate = (manifest_path.parent / candidate).resolve()
        else:
            candidate = candidate.resolve()
        paths.append(candidate)
    return paths


def collect_up_paths(args):
    paths = []
    if args.manifest is not None:
        manifest = require_file(args.manifest.expanduser().resolve())
        paths.extend(load_manifest_paths(manifest))

    for raw in args.up_files:
        paths.append(Path(raw).expanduser().resolve())

    unique = []
    seen = set()
    for path in paths:
        if path in seen:
            continue
        seen.add(path)
        unique.append(path)

    if not unique:
        raise ValueError("Provide at least one .up file via --up-files and/or --manifest")

    missing = [path for path in unique if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing .up files:\n" + "\n".join(str(path) for path in missing))
    return unique


def load_artifact(path: Path):
    with h5py.File(path, "r") as h5:
        if "/classes/protein" not in h5 or "/classes/environment" not in h5:
            raise ValueError(f"{path}: missing class datasets")
        if "/rbm/cross/radial_centers" not in h5 or "/rbm/cross/weights" not in h5:
            raise ValueError(f"{path}: missing cross-potential datasets")

        protein_classes = decode_bytes_array(h5["/classes/protein"][:]).tolist()
        env_classes = decode_bytes_array(h5["/classes/environment"][:]).tolist()
        centers = h5["/rbm/cross/radial_centers"][:].astype(np.float32)
        widths = h5["/rbm/cross/radial_widths"][:].astype(np.float32)
        weights = h5["/rbm/cross/weights"][:].astype(np.float32)
        cutoff = float(h5["/rbm/cross"].attrs["cutoff"])

    return {
        "protein_classes": protein_classes,
        "environment_classes": env_classes,
        "radial_centers": centers,
        "radial_widths": widths,
        "weights": weights,
        "cutoff": cutoff,
    }


def collect_indices(up_path: Path, artifact):
    protein_class_to_idx = {name: i for i, name in enumerate(artifact["protein_classes"])}
    env_class_to_idx = {name: i for i, name in enumerate(artifact["environment_classes"])}

    with h5py.File(up_path, "r") as h5:
        if "/input/atom_roles" not in h5:
            raise ValueError(f"{up_path}: missing /input/atom_roles")
        if "/input/type" not in h5:
            raise ValueError(f"{up_path}: missing /input/type")
        if "/input/hybrid_env_topology/protein_membership" not in h5:
            raise ValueError(f"{up_path}: missing /input/hybrid_env_topology/protein_membership")

        roles = decode_bytes_array(h5["/input/atom_roles"][:])
        types = decode_bytes_array(h5["/input/type"][:])
        membership = h5["/input/hybrid_env_topology/protein_membership"][:].astype(np.int32)

    if roles.shape[0] != types.shape[0] or roles.shape[0] != membership.shape[0]:
        raise ValueError(f"{up_path}: role/type/membership length mismatch")

    protein_mask = membership >= 0
    env_mask = ~protein_mask

    protein_indices = []
    protein_class_indices = []
    for idx, role in enumerate(roles.tolist()):
        role_name = role.strip()
        if not protein_mask[idx] or role_name not in protein_class_to_idx:
            continue
        protein_indices.append(idx)
        protein_class_indices.append(protein_class_to_idx[role_name])

    if not protein_indices:
        raise ValueError(f"{up_path}: no explicit N/CA/C/O backbone carriers found for injection")

    env_indices = []
    env_class_indices = []
    missing_types = set()
    for idx, atom_type in enumerate(types.tolist()):
        if not env_mask[idx]:
            continue
        type_name = atom_type.strip()
        if type_name not in env_class_to_idx:
            missing_types.add(type_name)
            continue
        env_indices.append(idx)
        env_class_indices.append(env_class_to_idx[type_name])

    if missing_types:
        raise ValueError(
            f"{up_path}: artifact is missing environment classes for types {sorted(missing_types)}"
        )
    if not env_indices:
        raise ValueError(f"{up_path}: no environment atoms found for injection")

    return (
        np.asarray(protein_indices, dtype=np.int32),
        np.asarray(protein_class_indices, dtype=np.int32),
        np.asarray(env_indices, dtype=np.int32),
        np.asarray(env_class_indices, dtype=np.int32),
    )


def inject_node(
    up_path: Path,
    artifact,
    protein_indices,
    protein_class_indices,
    env_indices,
    env_class_indices,
    overwrite_existing: bool,
):
    with h5py.File(up_path, "r+") as h5:
        input_grp = h5.require_group("input")
        pot_grp = input_grp.require_group("potential")
        node_name = "martini_rbm_cross_potential"
        if node_name in pot_grp:
            if not overwrite_existing:
                raise ValueError(f"{up_path}: {node_name} already exists and overwrite is disabled")
            del pot_grp[node_name]

        used_protein_classes = sorted(set(int(x) for x in protein_class_indices.tolist()))
        used_env_classes = sorted(set(int(x) for x in env_class_indices.tolist()))
        protein_reindex = {old: new for new, old in enumerate(used_protein_classes)}
        env_reindex = {old: new for new, old in enumerate(used_env_classes)}

        local_protein_class_indices = np.asarray(
            [protein_reindex[int(x)] for x in protein_class_indices.tolist()],
            dtype=np.int32,
        )
        local_env_class_indices = np.asarray(
            [env_reindex[int(x)] for x in env_class_indices.tolist()],
            dtype=np.int32,
        )
        local_weights = artifact["weights"][used_protein_classes][:, used_env_classes, :].astype(
            np.float32,
            copy=False,
        )
        local_protein_classes = np.asarray(
            [artifact["protein_classes"][idx] for idx in used_protein_classes],
            dtype=h5py.string_dtype(encoding="utf-8"),
        )
        local_env_classes = np.asarray(
            [artifact["environment_classes"][idx] for idx in used_env_classes],
            dtype=h5py.string_dtype(encoding="utf-8"),
        )

        grp = pot_grp.create_group(node_name)
        grp.attrs["arguments"] = np.asarray([b"pos"])
        grp.attrs["initialized"] = np.int8(1)
        grp.attrs["cutoff"] = np.float32(artifact["cutoff"])
        grp.create_dataset("protein_atom_indices", data=protein_indices)
        grp.create_dataset("protein_class_index", data=local_protein_class_indices)
        grp.create_dataset("env_atom_indices", data=env_indices)
        grp.create_dataset("env_class_index", data=local_env_class_indices)
        grp.create_dataset("radial_centers", data=artifact["radial_centers"])
        grp.create_dataset("radial_widths", data=artifact["radial_widths"])
        grp.create_dataset("weights", data=local_weights)
        grp.create_dataset("protein_classes", data=local_protein_classes)
        grp.create_dataset("environment_classes", data=local_env_classes)


def main():
    args = parse_args()
    artifact_path = require_file(args.artifact.expanduser().resolve())
    up_paths = collect_up_paths(args)
    artifact = load_artifact(artifact_path)

    required_protein = list(BACKBONE_CLASSES)
    if artifact["protein_classes"] != required_protein:
        raise ValueError(
            f"{artifact_path}: expected protein classes {required_protein}, "
            f"got {artifact['protein_classes']}"
        )

    for up_path in up_paths:
        (
            protein_indices,
            protein_class_indices,
            env_indices,
            env_class_indices,
        ) = collect_indices(up_path, artifact)
        inject_node(
            up_path=up_path,
            artifact=artifact,
            protein_indices=protein_indices,
            protein_class_indices=protein_class_indices,
            env_indices=env_indices,
            env_class_indices=env_class_indices,
            overwrite_existing=bool(args.overwrite_existing),
        )
        print(
            f"Injected martini_rbm_cross_potential into {up_path} "
            f"(protein={protein_indices.size}, env={env_indices.size})"
        )


if __name__ == "__main__":
    main()
