#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

export BILAYER_DIFF_BASE_DIR="${BILAYER_DIFF_BASE_DIR:-$SCRIPT_DIR/runs/mass_damping_followup}"
export BILAYER_DIFF_DAMPING_VALUES="${BILAYER_DIFF_DAMPING_VALUES:-5.0,8.0,12.0,16.0,24.0}"
export BILAYER_DIFF_MASS_SCALES="${BILAYER_DIFF_MASS_SCALES:-0.02,0.01,0.005,0.002,0.001}"
export BILAYER_DIFF_TEMPERATURE_VALUES="${BILAYER_DIFF_TEMPERATURE_VALUES:-0.70,0.80,0.90,1.00,1.10}"
export BILAYER_DIFF_REPLICATES="${BILAYER_DIFF_REPLICATES:-3}"

exec "$SCRIPT_DIR/submit_remote_round.sh" "$@"
